Import numpy

In [1]:
import numpy as np

In [2]:
# create an array
digits = np.array([
      [1, 2, 3],
      [4, 5, 6],
    [6, 7, 9],
    ])

In [3]:
 digits

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 9]])

In [4]:
# addition of two integers
a=2
b=4

In [5]:
c=a+b
c

6

In [6]:
# Study shape and axes of an array.
temperatures = np.array([
      29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
       12.6, 49.9, 38.6, 31.3, 9.2, 22.2
    ]).reshape(2, 2, 3)


In [7]:
In [3]: temperatures.shape

(2, 2, 3)

In [8]:
In [4]: temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [9]:
In [5]: np.swapaxes(temperatures, 1, 2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

In [10]:
table = np.array([
   ...:     [5, 3, 7, 1],
   ...:     [2, 6, 7 ,9],
   ...:     [1, 1, 1, 1],
   ...:     [4, 3, 2, 0],
   ...: ])


In [11]:
table.max()

9

In [12]:
 table.max(axis=0)

array([5, 6, 7, 9])

In [13]:
 table.max(axis=1)

array([7, 9, 1, 4])

In [14]:
#Study of Broadcasting with an array. 
A= np.arange(32).reshape(4, 1, 8)

In [15]:
A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [16]:
B = np.arange(48).reshape(1, 6, 8)


In [17]:
B

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [18]:
# Addition of two Arrays.
A+B

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

In [19]:
#Find the Square of an array.
square = np.array([
       [16, 3, 2, 13],
       [5, 10, 11, 8],
       [9, 6, 7, 12],
       [4, 15, 14, 1]
    ])

In [20]:
for i in range(4):
   ...:     assert square[:, i].sum() == 34
   ...:     assert square[i, :].sum() == 34
   ...:

In [21]:
assert square[:2, :2].sum() == 34


In [22]:
assert square[2:, :2].sum() == 34


In [23]:
 assert square[:2, 2:].sum() == 34

In [24]:
assert square[2:, 2:].sum() == 34

In [25]:
#Study of masking and filtering.
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

In [26]:
numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [27]:
mask = numbers % 4 == 0

In [28]:
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [29]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [30]:
by_four = numbers[numbers % 4 == 0]

In [31]:
by_four

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [32]:
from numpy.random import default_rng

In [33]:
rng = default_rng()

In [34]:
values = rng.standard_normal(10000)

In [35]:
 values[:5]

array([ 0.11543196,  0.13168618,  1.77149602, -0.50434497,  1.55829363])

In [36]:
std = values.std()

In [37]:
std

1.0163551599608251

In [38]:
filtered = values[(values > -2 * std) & (values < 2 * std)]

In [39]:
filtered.size

9542

In [40]:
 values.size

10000

In [41]:
filtered.size / values.size

0.9542

In [42]:
a = np.array([
       [1, 2],
    [3, 4],
    [5, 6],
   ])


In [43]:
#Transposing, Sorting, and Concatenating of arrays.
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [44]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [45]:
data = np.array([
   ...:     [7, 1, 4],
   ...:     [8, 6, 5],
   ...:     [1, 2, 3]
   ...: ])


In [46]:
np.sort(data)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [47]:
np.sort(data, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
np.sort(data, axis=0)

array([[1, 1, 3],
       [7, 2, 4],
       [8, 6, 5]])

In [49]:
a = np.array([
   ...:     [4, 8],
   ...:     [6, 1]
   ...: ])


In [50]:
b = np.array([
   ...:     [3, 5],
   ...:     [7, 2],
   ...: ])

In [51]:
np.hstack((a, b))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [52]:
np.vstack((b, a))

array([[3, 5],
       [7, 2],
       [4, 8],
       [6, 1]])

In [53]:
np.concatenate((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [54]:
np.concatenate((a, b), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

In [55]:
#Implementation of Maclaurin Series.
from math import e, factorial
fac = np.vectorize(factorial)

def e_x(x, terms=10):
    """Approximates e^x using a given number of terms of
    the Maclaurin series
    """
    n = np.arange(terms)
    return np.sum((x ** n) / fac(n))

if __name__ == "__main__":
    print("Actual:", e ** 3)  # Using e from the standard library

    print("N (terms)\tMaclaurin\tError")

    for n in range(1, 14):
        maclaurin = e_x(3, terms=n)
        print(f"{n}\t\t{maclaurin:.03f}\t\t{e**3 - maclaurin:.03f}")

Actual: 20.085536923187664
N (terms)	Maclaurin	Error
1		1.000		19.086
2		4.000		16.086
3		8.500		11.586
4		13.000		7.086
5		16.375		3.711
6		18.400		1.686
7		19.412		0.673
8		19.846		0.239
9		20.009		0.076
10		20.063		0.022
11		20.080		0.006
12		20.084		0.001
13		20.085		0.000


In [56]:
#Study of different Datatypes(numerical,String)
a = np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.single)
a

array([1. , 3. , 5.5, 7.7, 9.2], dtype=float32)

In [57]:
b = np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.uint8)
b

array([1, 3, 5, 7, 9], dtype=uint8)

In [58]:
names = np.array(["bob", "amy", "han"], dtype=str)

In [59]:
names

array(['bob', 'amy', 'han'], dtype='<U3')

In [60]:
names.itemsize

12

In [61]:
names = np.array(["bob", "amy", "han"])

In [62]:
names

array(['bob', 'amy', 'han'], dtype='<U3')

In [63]:
more_names = np.array(["bobo", "jehosephat"])

In [64]:
np.concatenate((names, more_names))

array(['bob', 'amy', 'han', 'bobo', 'jehosephat'], dtype='<U10')

In [65]:
names[2] = "jasica"

In [66]:
names

array(['bob', 'amy', 'jas'], dtype='<U3')

In [67]:
#Study of structured array
data = np.array([
     ("joe", 32, 6),
     ("mary", 15, 20),
    ("felipe", 80, 100),
    ("beyonce", 38, 9001),
   ], dtype=[("name", str, 10), ("age", int), ("power", int)])


In [68]:
data[0]

('joe', 32, 6)

In [69]:
data["name"]

array(['joe', 'mary', 'felipe', 'beyonce'], dtype='<U10')

In [70]:
data[data["power"] > 9000]["name"]

array(['beyonce'], dtype='<U10')

In [71]:
#numpy version
print("Numpy Version:",np.version.version)

Numpy Version: 1.21.5
