In [1]:
#Data Analysis with SciPy
# import numpy library
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [2]:
#Linear Algebra
#Determinant of a Matrix
# importing linalg function from scipy
from scipy import linalg
  
# Compute the determinant of a matrix
linalg.det(A)

2.999999999999997

In [3]:
#pivoted LU decomposition of a matrix
P, L, U = linalg.lu(A)
print(P)
print(L)
print(U)
# print LU decomposition
print(np.dot(L,U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         8.        ]
 [0.         0.85714286 1.85714286]
 [0.         0.         0.5       ]]
[[7. 8. 8.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [4]:
#Eigen values and eigen vectors of above matrix
eigen_values, eigen_vectors = linalg.eig(A)
print(eigen_values)
print(eigen_vectors)

[15.55528261+0.j -1.41940876+0.j -0.13587385+0.j]
[[-0.24043423 -0.67468642  0.51853459]
 [-0.54694322 -0.23391616 -0.78895962]
 [-0.80190056  0.70005819  0.32964312]]


In [5]:
#linear equations 
v = np.array([[2],[3],[5]])
print(v)
s = linalg.solve(A,v)
print(s)

[[2]
 [3]
 [5]]
[[-2.33333333]
 [ 3.66666667]
 [-1.        ]]


In [6]:
#Sparse Linear Algebra
from scipy import sparse
# Row-based linked list sparse matrix
A = sparse.lil_matrix((1000, 1000))
print(A)
  
A[0,:100] = np.random.rand(100)
A[1,100:200] = A[0,:100]
A.setdiag(np.random.rand(1000))
print(A)


  (0, 0)	0.233924393153503
  (0, 1)	0.22364183701676732
  (0, 2)	0.37914597004238004
  (0, 3)	0.2537451685852581
  (0, 4)	0.2946794827017569
  (0, 5)	0.5895388346702505
  (0, 6)	0.5049730465031124
  (0, 7)	0.4814506579720981
  (0, 8)	0.5670505992390058
  (0, 9)	0.8306874595432671
  (0, 10)	0.7026542973204873
  (0, 11)	0.19008728178723888
  (0, 12)	0.6936514992904729
  (0, 13)	0.3687531563486476
  (0, 14)	0.5462284131328174
  (0, 15)	0.03372825070971952
  (0, 16)	0.3764758352732749
  (0, 17)	0.4480816881786691
  (0, 18)	0.30252156093959337
  (0, 19)	0.7828571148948583
  (0, 20)	0.5016742328726606
  (0, 21)	0.7422497911279795
  (0, 22)	0.28322558525521035
  (0, 23)	0.22762533760428683
  (0, 24)	0.7726106111639771
  (0, 25)	0.1646912995454265
  (0, 26)	0.22565515276639025
  (0, 27)	0.8971717115821453
  (0, 28)	0.17632187759152784
  (0, 29)	0.44724807373184616
  (0, 30)	0.20992037971446986
  (0, 31)	0.38690424585380667
  (0, 32)	0.06556496334628592
  (0, 33)	0.290640869088885
  (0, 34)	0.

In [7]:
#Integration
import scipy.integrate
f= lambda x:np.exp(-x**2)
# print results
i = scipy.integrate.quad(f, 0, 1)
print(i)

(0.7468241328124271, 8.291413475940725e-15)


In [8]:
#Double Integrals
from scipy import integrate
f = lambda y, x: x*y**2
i = integrate.dblquad(f, 0, 2, lambda x: 0, lambda x: 1)
# print the results
print(i)

(0.6666666666666667, 7.401486830834377e-15)
